Repository WildCodeSchool/202302-orleans-php-project2-ahls, pull requests merged in 2023-04, with the labels that each got.

#2 initialisation
  config/style.css
  src/View/layout.html.twig
Labels: REVIEWED, CHANGES REQUESTED

#3 footer
  .gitignore
  config/style.css
  public/assets/css/footer.css
  public/assets/css/style.css
  public/assets/images/facebook.svg
  public/assets/images/instagram.svg
  public/assets/images/tiktok.svg
  public/assets/images/twitter.svg
  public/assets/images/youtube.svg
  src/View/components/_footer.html.twig
  src/View/layout.html.twig
Labels: REVIEWED

#4 Ajout de la navbar et du responsive
  public/assets/css/footer.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/logo_ahls.png
  public/assets/images/menu.svg
  src/View/components/_navbar.html.twig
  src/View/layout.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#10 fixed layout.html.twig
  src/View/layout.html.twig
Labels: REVIEWED

#9 demande de push dev to main
  .gitignore
  public/assets/css/footer.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/facebook.svg
  public/assets/images/instagram.svg
  public/assets/images/logo_ahls.png
  public/assets/images/menu.svg
  public/assets/images/tiktok.svg
  public/assets/images/twitter.svg
  public/assets/images/youtube.svg
  src/View/components/_footer.html.twig
  src/View/components/_navbar.html.twig
  src/View/layout.html.twig
Labels: REVIEWED

#16 Ajout des archives
  public/assets/css/newspaper/archive.css
  public/assets/css/newspaper/newspaper.css
  src/View/Newspaper/archive.html.twig
  src/View/Newspaper/index.html.twig
Labels: REVIEWED

#19 partners
  database.sql
  public/assets/css/home/partner/partner.css
  src/Controller/HomeController.php
  src/Model/PartnerManager.php
  src/View/Home/index.html.twig
  src/routes.php
Labels: REVIEWED

#11 Fix footer
  database.sql
  public/assets/css/association.css
  public/assets/css/footer.css
  public/assets/css/style.css
  public/assets/images/boardMember_placeholder.jpg
  src/Controller/AssociationController.php
  src/Model/BoardMemberManager.php
  src/View/Association/index.html.twig
  src/routes.php
Labels: REVIEWED, CONFLICTS RESOLVED

#20 html et css presentation association
  database.sql
  public/assets/css/association.css
  public/assets/css/style.css
  public/assets/images/chaufferie.jpg
  src/View/Association/index.html.twig
Labels: REVIEWED

#5 news feed block for homepage
  $myConnection.session.sql
  .gitignore
  .tours/code_tour_menu.png
  .tours/photo-1632178151697-fd971baa906f.jpg
  .tours/routing.tour
  .tours/routing_meme.jpg
  .tours/schema_1_routing.png
  .tours/simple-mvc.tour
  .tours/simple_MVC.png
  ahls.db
  config/style.css
  database.sql
  public/assets/css/actuality.css
  public/assets/images/l-indien-mars-23.webp
  public/assets/images/vector.png
  src/Controller/ActualityController.php
  src/Controller/HomeController.php
  src/Model/ActualityManager.php
  src/View/Home/index.html.twig
  src/View/Item/index.html.twig
  src/View/layout.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED

#21 dev to main
  $myConnection.session.sql
  .gitignore
  .tours/code_tour_menu.png
  .tours/photo-1632178151697-fd971baa906f.jpg
  .tours/routing.tour
  .tours/routing_meme.jpg
  .tours/schema_1_routing.png
  .tours/simple-mvc.tour
  .tours/simple_MVC.png
  ahls.db
  config/style.css
  database.sql
  public/assets/css/actuality.css
  public/assets/css/association.css
  public/assets/css/footer.css
  public/assets/css/home/header.css
  public/assets/css/home/partner/partner.css
  public/assets/css/newspaper/archive.css
  public/assets/css/newspaper/newspaper.css
  public/assets/css/style.css
  public/assets/images/boardMember_placeholder.jpg
  public/assets/images/chaufferie.jpg
  public/assets/images/cover137_placeholder.png
  public/assets/images/indien.jpg
  public/assets/images/l-indien-mars-23.webp
  public/assets/images/vector.png
  src/Controller/ActualityController.php
  src/Controller/AssociationController.php
  src/Controller/HomeController.php
  src/Controller/NewspaperController.php
  src/Model/ActualityManager.php
  src/Model/BoardMemberManager.php
  src/Model/NewspaperManager.php
  src/Model/PartnerManager.php
  src/View/Association/index.html.twig
  src/View/Home/index.html.twig
  src/View/Item/index.html.twig
  src/View/Newspaper/archive.html.twig
  src/View/Newspaper/index.html.twig
  src/View/components/_navbar.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: REVIEWED

#24 résolution erreurs css
  public/assets/.DS_Store
  public/assets/css/association.css
  public/assets/css/home/actuality.css
  public/assets/css/home/partner.css
  public/assets/css/style.css
  public/assets/images/.DS_Store
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: REVIEWED

#25 Présentation du 28/04/23
  public/assets/.DS_Store
  public/assets/css/association.css
  public/assets/css/home/actuality.css
  public/assets/css/home/partner.css
  public/assets/css/style.css
  public/assets/images/.DS_Store
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: REVIEWED

#22 magazine_presentation html css terminés
  public/assets/css/association.css
  public/assets/images/Indien_137_couverture.jpg
  src/View/Association/index.html.twig
  src/View/components/_navbar.html.twig
Labels: REVIEWED, CONFLICTS RESOLVED
