Repository WildCodeSchool/202302-orleans-php-project2-ahls, pull requests merged in 2023-05, with the labels that each got.

#29 Contact formulaire cette fois c'est la bonne
  public/assets/css/contact.css
  public/assets/css/style.css
  src/Controller/ContactController.php
  src/View/Contact/index.html.twig
  src/View/components/_navbar.html.twig
  src/routes.php
Labels: REVIEWED

#30 history_association html et css terminés
  src/View/Association/index.html.twig
Labels: REVIEWED

#23 ajouter un partenaire
  database.sql
  public/assets/css/admin/addPartner.css
  public/uploads/.gitignore
  src/Controller/AdminPartnerController.php
  src/Model/PartnerManager.php
  src/View/Admin/Partner/_form.html.twig
  src/View/Admin/Partner/add.html.twig
  src/routes.php
Labels: REVIEWED, CONFLICTS RESOLVED

#31 admin list journaux
  public/assets/css/admin.css
  src/Controller/AdminNewspaperController.php
  src/View/Admin/Newspaper/index.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: REVIEWED, CONFLICTS RESOLVED

#36 S04US37 add finish
  src/Controller/AdminAssociationController.php
  src/Model/BoardMemberManager.php
  src/View/Admin/Association/create.html.twig
  src/View/Admin/Association/index.html.twig
  src/routes.php
Labels: REVIEWED

#35 Ajouter des journaux
  database.sql
  public/assets/css/admin.css
  src/Controller/AdminNewspaperController.php
  src/Model/NewspaperManager.php
  src/View/Admin/Newspaper/_form.html.twig
  src/View/Admin/Newspaper/add.html.twig
  src/View/Admin/Newspaper/index.html.twig
  src/View/Newspaper/archive.html.twig
  src/View/Newspaper/index.html.twig
  src/routes.php
Labels: REVIEWED

#37 admin_update finish
  src/Controller/AdminAssociationController.php
  src/Model/BoardMemberManager.php
  src/View/Admin/Association/_form.html.twig
  src/View/Admin/Association/create.html.twig
  src/View/Admin/Association/index.html.twig
  src/View/Admin/Association/update.html.twig
  src/routes.php
Labels: REVIEWED

#40 S04US36_admin_delete finish
  src/Controller/AdminAssociationController.php
  src/View/Admin/Association/index.html.twig
  src/routes.php
Labels: REVIEWED

#41 S04
  .gitignore
  Dockerfile
  database.sql
  docker-entry.sh
  public/assets/css/admin.css
  public/assets/css/admin/addPartner.css
  public/assets/css/association.css
  public/assets/css/contact.css
  public/assets/css/style.css
  public/assets/images/Indien_137_couverture.jpg
  public/assets/images/edit.svg
  public/uploads/.gitignore
  src/Controller/AdminAssociationController.php
  src/Controller/AdminNewspaperController.php
  src/Controller/AdminPartnerController.php
  src/Controller/ContactController.php
  src/Model/BoardMemberManager.php
  src/Model/NewspaperManager.php
  src/Model/PartnerManager.php
  src/View/Admin/Association/_form.html.twig
  src/View/Admin/Association/create.html.twig
  src/View/Admin/Association/index.html.twig
  src/View/Admin/Association/update.html.twig
  src/View/Admin/Newspaper/_form.html.twig
  src/View/Admin/Newspaper/add.html.twig
  src/View/Admin/Newspaper/edit.html.twig
  src/View/Admin/Newspaper/index.html.twig
  src/View/Admin/Partner/_form.html.twig
  src/View/Admin/Partner/add.html.twig
  src/View/Association/index.html.twig
  src/View/Contact/index.html.twig
  src/View/Newspaper/archive.html.twig
  src/View/Newspaper/index.html.twig
  src/View/components/_navbar.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: REVIEWED

#43 Ajout de delete des journaux
  public/assets/css/admin.css
  src/Controller/AdminNewspaperController.php
  src/View/Admin/Newspaper/index.html.twig
  src/View/Admin/icons/delete.svg
  src/View/Admin/icons/edit.svg
  src/routes.php
Labels: REVIEWED

#42 legal_notice html css finish
  public/assets/css/legalNotice.css
  src/Controller/LegalNoticeController.php
  src/View/LegalNotice/index.html.twig
  src/View/components/_footer.html.twig
  src/routes.php
Labels: REVIEWED

#47 admin_home_page html css finish
  public/assets/css/admin/adminHomePage.css
  src/Controller/AdminHomePageController.php
  src/View/Admin/HomePage/index.html.twig
  src/View/adminLayout.html.twig
  src/View/components/_navbar_admin.html.twig
  src/routes.php
Labels: REVIEWED

#49 modif header de l'accueil et des articles journaux
  public/assets/css/home/header.css
  public/assets/css/newspaper/newspaper.css
Labels: REVIEWED

#48 sidebar admin html css finish
  public/assets/css/association.css
  src/View/Association/index.html.twig
Labels: REVIEWED

#50 fix css admin list board_member
  public/assets/css/admin/adminListBoardMember.css
  src/View/Admin/Association/index.html.twig
Labels: REVIEWED

#45 S05 u25 create actuality
  $myConnection.session.sql
  .gitignore
  ahls.db
  database.sql
  public/assets/css/admin/addActuality.css
  public/assets/css/home/actuality.css
  public/assets/css/home/magazine.css
  public/assets/css/style.css
  public/assets/images/cover136_placeholder.png
  src/Controller/ActualityController.php
  src/Controller/AdminActualityController.php
  src/Controller/HomeController.php
  src/Model/ActualityManager.php
  src/Model/NewspaperManager.php
  src/View/Actuality/add_article.html.twig
  src/View/Actuality/admin_actuality.html.twig
  src/View/Admin/HomePage/index.html.twig
  src/View/Home/index.html.twig
  src/View/components/_navbar_admin.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: REVIEWED, CONFLICTS RESOLVED

#51 fix_admin_add_board_member finish
  public/assets/css/admin/adminAddBoardMember.css
  src/View/Admin/Association/create.html.twig
Labels: REVIEWED

#54 fix finish
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: REVIEWED

#55 dev to main
  $myConnection.session.sql
  .gitignore
  ahls.db
  database.sql
  public/assets/css/admin.css
  public/assets/css/admin/addActuality.css
  public/assets/css/admin/adminAddBoardMember.css
  public/assets/css/admin/adminHomePage.css
  public/assets/css/admin/adminListBoardMember.css
  public/assets/css/association.css
  public/assets/css/home/actuality.css
  public/assets/css/home/header.css
  public/assets/css/home/magazine.css
  public/assets/css/legalNotice.css
  public/assets/css/newspaper/newspaper.css
  public/assets/css/style.css
  public/assets/images/cover136_placeholder.png
  src/Controller/ActualityController.php
  src/Controller/AdminActualityController.php
  src/Controller/AdminHomePageController.php
  src/Controller/AdminNewspaperController.php
  src/Controller/HomeController.php
  src/Controller/LegalNoticeController.php
  src/Model/ActualityManager.php
  src/Model/NewspaperManager.php
  src/View/Actuality/add_article.html.twig
  src/View/Actuality/admin_actuality.html.twig
  src/View/Admin/Association/create.html.twig
  src/View/Admin/Association/index.html.twig
  src/View/Admin/HomePage/index.html.twig
  src/View/Admin/Newspaper/index.html.twig
  src/View/Admin/icons/delete.svg
  src/View/Admin/icons/edit.svg
  src/View/Association/index.html.twig
  src/View/Home/index.html.twig
  src/View/LegalNotice/index.html.twig
  src/View/adminLayout.html.twig
  src/View/components/_footer.html.twig
  src/View/components/_navbar_admin.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: REVIEWED

#65 fixed add actuality header location
  src/Controller/AdminActualityController.php
Labels: REVIEWED

#66 responsive admin list
  public/assets/css/admin/adminListBoardMember.css
Labels: REVIEWED

#67 fix_footer finish
  public/assets/css/footer.css
  src/View/components/_footer.html.twig
Labels: REVIEWED

#68 Modif des journaux et de la BDD
  database.sql
  public/assets/css/newspaper/newspaper.css
  public/assets/images/journaux_placeholder.jpg
  src/View/Newspaper/index.html.twig
Labels: REVIEWED

#69 dev to main
  database.sql
  public/assets/css/admin/adminListBoardMember.css
  public/assets/css/footer.css
  public/assets/css/newspaper/newspaper.css
  public/assets/images/journaux_placeholder.jpg
  src/Controller/AdminActualityController.php
  src/View/Newspaper/index.html.twig
  src/View/components/_footer.html.twig
Labels: REVIEWED

#70 fix du CSS Admin : addActuality
  public/assets/css/admin/addActuality.css
  src/View/Actuality/add_article.html.twig
Labels: REVIEWED

#71 fixed admin actuality css index section
  public/assets/css/admin/adminActuality.css
  src/View/Actuality/admin_actuality.html.twig
Labels: REVIEWED

#72 association css fix
  public/assets/css/association.css
  public/assets/css/home/actuality.css
Labels: REVIEWED

#73 fix partners css home
  public/assets/css/home/partner.css
  src/View/Home/index.html.twig
Labels: REVIEWED

#74 fix_header_image
  public/assets/css/home/header.css
  public/assets/images/gymnaseLaSource.jpeg
Labels: REVIEWED

#52 fixed articles url
  src/View/Home/index.html.twig
Labels: REVIEWED

#75 fixed cover img hover effect in magazine.css
  public/assets/css/home/magazine.css
Labels: REVIEWED

#77 remise en forme des journaux
  public/assets/css/newspaper/archive.css
  public/assets/css/newspaper/newspaper.css
  src/View/Newspaper/archive.html.twig
Labels: REVIEWED

#76 fixed title sizes on homepage
  public/assets/css/home/actuality.css
  public/assets/css/home/magazine.css
Labels: REVIEWED, CONFLICTS RESOLVED

#79 supp de accueil navbar
  src/View/components/_navbar.html.twig
Labels: REVIEWED

#78 header blur
  public/assets/css/home/header.css
  src/View/Home/index.html.twig
Labels: CHANGES REQUESTED

#80 fix css admin article
  public/assets/css/admin/addActuality.css
  public/assets/css/admin/adminActuality.css
  src/View/Actuality/add_article.html.twig
  src/View/Actuality/admin_actuality.html.twig
Labels: REVIEWED
